str = "akash Bhosale"
print(str)
print(len(str))
print(str.count('a'))
print(str.lower())
print(str.upper())
print(str.islower())
print(str.isupper())
print(str.replace("a","e"))
print(str.split(" "))
print(str.startswith("a"))
print(str.endswith("e"))
print(str.find("a"))
print(str.index("a"))
print(str.isalnum())
print(str.isalpha())
print(str.isdigit())
print(str.isnumeric())
print(str.isspace())
print(str.istitle())
print(str.isprintable())
print(str.isascii())

